id: IB44CB601
default_language: en
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-10 00:29:33.937068
last_modified: 2023-02-10 00:29:33.937196
source_metadata:
  title: 'Nāgārjuna: Mūlamadhyamakakārikā'
  language: en
bases:
  308F:
    base_file: 308F.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
